from bunnyhop import Bunny

b = Bunny('<api_key>')
print("Test Billing\n")
print(f"Billing Get: \n {b.Billing.get()}")
print(f"Billing Apply Code: \n {b.Billing.applycode(couponCode='somecode123')}")
print("\nEnd Test Billing\n")
print("Test Purge\n")
print(f"Purge Create: \n {b.Purge.create(url='https://myzone.b-cdn.net/style.css')}")
print("\nEnd Test Purge\n")
print("Test Stats\n")
print(f"Stats Get: \n {b.Stats.get(dateFrom='2018-12-01', dateTo='2020-01-01', pullZone='example-zone', serverZoneId='serverZoneID')}")
print("\nEnd Test Stats\n")
print("Test Storage\n")
print(f"Storage Create: \n {b.Storage.create(name='example-a', main_storage_region='NY', replica_regions=['DE', 'SG', 'SYD'])}")
print(f"Storage All: \n {b.Storage.all()}")
print(f"Storage Delete: \n {b.Storage.delete(1234)}")
print(f"Storage Get: \n {b.Storage.get(1234)}")
print("\nEnd Test Storage\n")
print("Test Zone\n")
print(f"Zone Get: \n {b.Zone.get(id='myzone')}")
print(f"Zone Create: \n {b.Zone.create(Name='myzone',Type=0,OriginUrl='https://example.org',StorageZoneId='storage-zone-id')}")
print(f"Zone All: \n {b.Zone.list()}")
print(f"Zone Update: \n {b.Zone.update(id=123)}")
print(f"Zone Delete: \n {b.Zone.delete(id=123)}")
print(f"Zone PurgeCache: \n {b.Zone.purge(id='myzone')}")
print(f"Zone CreateEdge: \n {b.Zone.create_edge_rule(id='myzone')}")
print("\nEnd Test Zone\n")
print("Test StorageZone\n")
zone = b.StorageZone.get(1234)
print(f"storageZone name : \n {zone.zone_name}")
print(f"storageZone all : \n {zone.all('path')}")
print(f"storageZone file : \n {zone.get('path', 'filename')}")
print(f"storageZone delete : \n {zone.delete('path','filename')}")
print(f"storageZone upload : \n {zone.upload_file('path','filename')}")
print(f"storageZone createfile : \n {zone.create_file('base.css', 'body {background-color: powderblue;}')}")
json = {'first_name':'Michael', 'last_name': 'Jordan'}
print(f"storageZone createfile : \n {zone.create_json('23.json', json)}")
print("\nEnd Test StorageZone\n")
