name: Python application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
      run: docker-compose pull
        continue-on-error: true
      run: docker-compose build

      - name: Run Unit Tests
      run: docker-compose run web poetry run python -m unittest

      - name: Publish to PyPi
      if: github.ref == 'refs/heads/master'
      run: docker-compose run web poetry build && docker-compose run web poetry publish --username=${{ secrets.PYPI_USERNAME }} --password=${{ secrets.PYPI_PASSWORD }}

      - name: Create pdoc
      run: docker-compose run web poetry run python -m pdoc -o ./docs bunnyhop

      # - name: Upload docs to S3
      # run: 
